import { StyleSheet } from 'react-native';

// 여행 일정 수정 화면의 입력·동행자·미션 관리 스타일입니다.
export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    flex: 1,
  },
  center: {
    alignItems: 'center',
    backgroundColor: '#fff',
    flex: 1,
    justifyContent: 'center',
  },
  sectionTitle: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 28,
  },
  inputBox: {
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 12,
    flexDirection: 'row',
    height: 51,
    marginTop: 18,
    paddingHorizontal: 22,
  },
  input: {
    color: '#8A9194',
    flex: 1,
    fontSize: 16,
  },
  clearText: {
    alignItems: 'center',
    backgroundColor: '#8A9194',
    borderRadius: 20,
    color: '#ffffff',
    fontSize: 19,
    height: 22,
    lineHeight: 22,
    textAlign: 'center',
    width: 22,
  },
  inputMessage: {
    color: '#D06958',
    fontSize: 11,
    marginLeft: 12,
    marginTop: 6,
  },
  periodTitle: {
    marginTop: 38,
  },
  periodDisabled: {
    opacity: 0.55,
  },
  periodRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  dateBox: {
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 12,
    flex: 1,
    flexDirection: 'row',
    height: 47,
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  changedDateBox: {
    backgroundColor: '#E3F0F6',
  },
  dateText: {
    color: '#8A9194',
    fontSize: 16,
    fontWeight: '500',
  },
  changedDateText: {
    color: '#10161F',
  },
  chevronIcon: {
    height: 5,
    width: 8,
  },
  wave: {
    color: '#10161F',
    fontSize: 16,
  },
  durationText: {
    color: '#8A9194',
    fontSize: 12,
    marginLeft: 12,
    marginTop: 10,
  },
  companionTitle: {
    marginTop: 38,
  },
  peopleRow: {
    gap: 8,
    paddingBottom: 2,
    paddingTop: 20,
  },
  personItem: {
    alignItems: 'center',
    width: 67,
  },
  addPerson: {
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 44,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  plus: {
    color: '#8A9194',
    fontSize: 20,
    fontWeight: '500',
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: '#DCEAF0',
    borderRadius: 44,
    height: 56,
    justifyContent: 'center',
    position: 'relative',
    width: 56,
    zIndex: 2,
  },
  crown: {
    elevation: 5,
    height: 20,
    position: 'absolute',
    right: -5,
    top: -2,
    width: 20,
    zIndex: 5,
  },
  removePerson: {
    alignItems: 'center',
    backgroundColor: '#10161F',
    borderRadius: 15,
    elevation: 6,
    height: 20,
    justifyContent: 'center',
    position: 'absolute',
    right: -5,
    top: -2,
    width: 20,
    zIndex: 6,
  },
  removePersonText: {
    color: '#ffffff',
    fontSize: 21,
    lineHeight: 24,
  },
  personName: {
    color: '#8A9194',
    fontSize: 12,
    marginTop: 8,
    maxWidth: 82,
    textAlign: 'center',
  },
  missionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 18,
  },
  missionHeaderText: {
    color: '#10161F',
    fontSize: 21,
    fontWeight: '700',
  },
  missionChevron: {
    color: '#10161F',
    fontSize: 30,
    marginTop: 4,
  },
  missionSubtitle: {
    color: '#8A9194',
    fontSize: 12,
    marginTop: 8,
  },
  missionList: {
    backgroundColor: '#F8FAFB',
    borderRadius: 18,
    gap: 10,
    marginTop: 18,
    padding: 12,
  },
  emptyMission: {
    color: '#8A9194',
    padding: 14,
  },
  missionItem: {
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 14,
    flexDirection: 'row',
    gap: 8,
    padding: 12,
  },
  missionCopy: {
    flex: 1,
  },
  missionTitle: {
    color: '#26343B',
    fontSize: 15,
    fontWeight: '600',
  },
  missionDate: {
    color: '#8A9194',
    fontSize: 12,
    marginTop: 4,
  },
  missionAction: {
    alignItems: 'center',
    borderRadius: 16,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  disabledAction: {
    opacity: 0.35,
  },
  deleteText: {
    color: '#D06958',
    fontSize: 20,
  },
  message: {
    color: '#D06958',
    fontSize: 13,
    marginTop: 18,
  },
  bottomBar: {
    backgroundColor: '#fff',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: '#E3F0F6',
    borderRadius: 42,
    height: 63,
    justifyContent: 'center',
  },
  activeSaveButton: {
    backgroundColor: '#63B5CD',
  },
  saveText: {
    color: '#6EA4BF',
    fontSize: 16,
    fontWeight: '600',
  },
  activeSaveText: {
    color: '#FFFFFF',
  },
});
