// 일정 목록 화면과 일정 카드에서 공유하는 스타일입니다.

import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { backgroundColor: '#ffffff', flex: 1 },
  scrollArea: { flex: 1 },
  content: { paddingTop: 34 },
  topBar: { alignItems: 'center', flexDirection: 'row', height: 48, justifyContent: 'space-between' },
  backButton: { alignItems: 'flex-start', height: 48, justifyContent: 'center', width: 48 },
  backIcon: { color: '#10161F', fontSize: 42, lineHeight: 42 },
  topTitle: { color: '#10161F', flex: 1, fontSize: 16, fontWeight: '600', lineHeight: 24, textAlign: 'center' },
  topSpacer: { width: 48 },
  createCard: { backgroundColor: '#E9F8FF', borderRadius: 32, minHeight: 174, paddingHorizontal: 24, paddingVertical: 18 },
  createTopRow: { alignItems: 'center', flexDirection: 'row', gap: 20, justifyContent: 'center', marginBottom: 18 },
  birdIcon: { height: 88, width: 88 },
  createCopy: { flex: 1, minWidth: 0 },
  createTitle: { color: '#10161F', fontSize: 16, fontWeight: '600', lineHeight: 18 },
  createSubtitle: { color: '#8A9194', fontSize: 12, fontWeight: '400', lineHeight: 16, marginTop: 10 },
  createButton: { alignItems: 'center', alignSelf: 'stretch', backgroundColor: '#63B5CD', borderRadius: 999, height: 46, justifyContent: 'center' },
  createButtonText: { color: '#ffffff', fontSize: 12, fontWeight: '600' },
  sectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 48, minHeight: 34 },
  sectionTitle: { color: '#000000', fontSize: 16, fontWeight: '600', lineHeight: 30 },
  sectionActions: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  moreButton: { alignItems: 'center', alignSelf: 'center', height: 30, justifyContent: 'center', minWidth: 26, paddingTop: 0 },
  moreIcon: { color: '#8A9194', fontSize: 13, fontWeight: '900', letterSpacing: 0, lineHeight: 13, textAlign: 'center', textAlignVertical: 'center' },
  doneText: { color: '#6EA4BF', fontSize: 14, fontWeight: '800', lineHeight: 20 },
  scheduleList: { gap: 12, marginTop: 18 },
  scheduleCardWrap: { position: 'relative', zIndex: 1 },
  draggingScheduleCardWrap: { elevation: 8, zIndex: 10 },
  crownBadge: { height: 15, marginLeft: 8, width: 15 },
  scheduleCard: { alignItems: 'center', backgroundColor: '#E9F8FF', borderRadius: 20, flexDirection: 'row', minHeight: 88, paddingHorizontal: 24, paddingVertical: 20 },
  creatorScheduleCard: { backgroundColor: '#EAF6FB' },
  closedScheduleCard: { backgroundColor: '#F6F9FB' },
  editingScheduleCard: { borderColor: '#DAE5EA', borderWidth: 1 },
  scheduleBody: { alignItems: 'center', flex: 1, flexDirection: 'row', minWidth: 0 },
  scheduleThumb: { alignItems: 'center', backgroundColor: '#D8EEF7', borderRadius: 18, height: 48, justifyContent: 'center', width: 48 },
  scheduleThumbText: { color: '#4D8DA9', fontSize: 16, fontWeight: '600' },
  scheduleInfo: { flex: 1, marginLeft: 18, minWidth: 0 },
  scheduleTitleRow: { alignItems: 'center', flexDirection: 'row', minWidth: 0 },
  scheduleTitle: { color: '#000000', flexShrink: 1, minWidth: 0, fontSize: 16, fontWeight: '500', lineHeight: 22 },
  scheduleDate: { color: '#7A909A', fontSize: 12, fontWeight: '400', lineHeight: 18, marginTop: 4 },
  chevron: { color: '#8A9194', fontSize: 44, fontWeight: '300', lineHeight: 44, marginLeft: 16 },
  galleryIcon: { height: 22, marginLeft: 16, width: 22 },
  editActions: { alignItems: 'center', flexDirection: 'row', gap: 12, marginLeft: 12 },
  deletePill: { alignItems: 'center', backgroundColor: '#FFF0EC', borderRadius: 999, justifyContent: 'center', minHeight: 38, minWidth: 58, paddingHorizontal: 12 },
  deletePillText: { color: '#D06958', fontSize: 13, fontWeight: '800' },
  dragHandleBox: { alignItems: 'center', height: 44, justifyContent: 'center', width: 34 },
  dragHandle: { color: '#9AA1A5', fontSize: 24, fontWeight: '800', lineHeight: 26 },
  pinnedLabel: { color: '#6EA4BF', fontSize: 12, fontWeight: '700', marginLeft: 12 },
  emptyBox: { alignItems: 'center', backgroundColor: '#F6F9FB', borderRadius: 18, marginTop: 18, paddingHorizontal: 24, paddingVertical: 24 },
  emptyTitle: { color: '#10161F', fontSize: 14, fontWeight: '600' },
  emptyDescription: { color: '#8A9194', fontSize: 12, fontWeight: '500', lineHeight: 18, marginTop: 2, textAlign: 'center' },
  messageText: { color: '#D06958', fontSize: 12, fontWeight: '600', lineHeight: 18, marginTop: 14 },
});
