import { StyleSheet } from 'react-native';

// 여행 초대 화면의 레이아웃과 상태별 표현을 담당하는 스타일입니다.
export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#ffffff',
    flex: 1,
  },
  centerContainer: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    flex: 1,
    gap: 16,
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  content: {
    flex: 1,
  },
  heading: {
    color: '#000000',
    fontWeight: '600',
    lineHeight: 30,
  },
  description: {
    color: '#AEAEAE',
    fontSize: 12,
    marginTop: 8,
  },
  scheduleSummary: {
    backgroundColor: '#F4F7F8',
    borderRadius: 14,
    gap: 6,
    marginTop: 30,
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  scheduleName: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '800',
  },
  scheduleMeta: {
    color: '#6D7478',
    fontSize: 12,
    lineHeight: 17,
  },
  companions: {
    flexDirection: 'row',
    gap: 14,
  },
  companionItem: {
    alignItems: 'center',
    gap: 8,
  },
  addAvatar: {
    alignItems: 'center',
    backgroundColor: '#e9ecef',
    borderRadius: 999,
    justifyContent: 'center',
  },
  addIcon: {
    color: '#409CB7',
    fontSize: 27,
    fontWeight: '400',
    lineHeight: 40,
  },
  avatar: {
    borderRadius: 999,
  },
  activeLabel: {
    color: '#409CB7',
    fontSize: 12,
  },
  mutedLabel: {
    color: '#b2b2b2',
    fontSize: 12,
  },
  inlineMessageText: {
    color: '#D06958',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 12,
  },
  startButton: {
    alignItems: 'center',
    backgroundColor: '#409CB7',
    borderRadius: 999,
    justifyContent: 'center',
    shadowColor: '#409CB7',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.26,
    shadowRadius: 18,
  },
  startButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '500',
  },
  modalBackdrop: {
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  invitePanel: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    overflow: 'hidden',
    paddingTop: 23,
  },
  invitePanelTitle: {
    color: '#10161F',
    fontSize: 15,
    fontWeight: '700',
    paddingHorizontal: 40,
  },
  inviteOptionsRow: {
    flexDirection: 'row',
    gap: 22,
    paddingHorizontal: 40,
    paddingTop: 27,
  },
  inviteOption: {
    alignItems: 'center',
    gap: 7,
    width: 72,
  },
  kakaoInviteAvatar: {
    alignItems: 'center',
    backgroundColor: '#FBE339',
    borderRadius: 999,
    height: 62,
    justifyContent: 'center',
    width: 62,
  },
  kakaoTalkText: {
    color: '#3A2D00',
    fontSize: 10,
    fontWeight: '800',
  },
  inviteContactAvatar: {
    borderRadius: 999,
    height: 62,
    position: 'relative',
    width: 62,
  },
  contactKakaoBadge: {
    alignItems: 'center',
    backgroundColor: '#FBE339',
    borderColor: '#ffffff',
    borderRadius: 999,
    borderWidth: 2,
    bottom: 1,
    height: 21,
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    width: 21,
  },
  contactKakaoText: {
    color: '#3A2D00',
    fontSize: 5,
    fontWeight: '800',
  },
  inviteOptionText: {
    color: '#72787D',
    fontSize: 12,
    fontWeight: '500',
  },
  inviteDivider: {
    backgroundColor: '#E8ECEF',
    height: 1,
    marginTop: 20,
  },
  copyInviteButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#E9EDF0',
    borderRadius: 16,
    flexDirection: 'row',
    height: 64,
    justifyContent: 'space-between',
    marginTop: 18,
    paddingHorizontal: 28,
    width: '77%',
  },
  copyInviteText: {
    color: '#626E75',
    fontSize: 13,
    fontWeight: '600',
  },
  inviteMessageText: {
    color: '#409CB7',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 10,
    paddingHorizontal: 40,
  },
  previewTitle: {
    color: '#10161F',
    fontSize: 23,
    fontWeight: '800',
  },
  previewCard: {
    alignItems: 'center',
    backgroundColor: '#F4F7F8',
    borderRadius: 16,
    gap: 8,
    paddingHorizontal: 22,
    paddingVertical: 22,
    width: '100%',
  },
  roomName: {
    color: '#10161F',
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  previewText: {
    color: '#6D7478',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  centerMessage: {
    color: '#6D7478',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#409CB7',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 38,
  },
  disabledButton: {
    opacity: 0.45,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
});
