import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#f1f8fb',
    flex: 1,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 44,
    justifyContent: 'space-between',
    marginBottom: 48,
  },
  backButton: {
    alignItems: 'flex-start',
    height: 44,
    justifyContent: 'center',
    width: 48,
  },
  backIcon: {
    color: '#202124',
    fontSize: 44,
    lineHeight: 44,
  },
  headerSpacer: {
    width: 48,
  },
  title: {
    color: '#111111',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
  },
  categoryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    marginBottom: 38,
  },
  categoryButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 13,
    shadowColor: '#000000',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
  },
  selectedCategoryButton: {
    backgroundColor: '#64ABBF',
  },
  categoryIcon: {
    height: 24,
    width: 24,
  },
  categoryLabel: {
    color: '#224853',
    fontSize: 12,
    fontWeight: '500',
  },
  selectedCategoryLabel: {
    color: '#ffffff',
    fontWeight: '700',
  },
  mapArea: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    marginBottom: 28,
  },
  mapPieceStage: {
    height: '100%',
    position: 'relative',
    width: '100%',
  },
  mapImage: {
    height: '100%',
    opacity: 0.9,
    width: '100%',
  },
  districtTouchLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  districtTouchTarget: {
    backgroundColor: 'transparent',
    position: 'absolute',
  },
  mapLoadingIndicator: {
    left: '50%',
    position: 'absolute',
    top: '50%',
    transform: [{ translateX: -10 }, { translateY: -10 }],
  },
  mapStatusBox: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    borderRadius: 14,
    gap: 7,
    left: '50%',
    minWidth: 156,
    paddingHorizontal: 14,
    paddingVertical: 10,
    position: 'absolute',
    top: '50%',
    transform: [{ translateX: -78 }, { translateY: -24 }],
  },
  mapStatusText: {
    color: '#5e686d',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  overlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(20, 25, 27, 0.72)',
    bottom: 0,
    justifyContent: 'flex-start',
    left: 0,
    paddingHorizontal: 18,
    paddingTop: 132,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  overlayTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '400',
    marginBottom: 20,
  },
  frameDeck: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  missionFrame: {
    position: 'absolute',
    zIndex: 1,
  },
  backFrameLeft: {
    opacity: 1,
    transform: [{ translateX: -4 }, { translateY: 7 }, { rotate: '-11deg' }],
  },
  backFrameRight: {
    opacity: 1,
    transform: [{ translateX: 3 }, { translateY: 7 }, { rotate: '11deg' }],
  },
  frontMissionCard: {
    alignItems: 'center',
    elevation: 0,
    justifyContent: 'center',
    position: 'absolute',
    zIndex: 3,
  },
  pagination: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
    marginTop: 10,
    transform: [{ translateY: -32 }],
  },
  pageDot: {
    backgroundColor: 'rgba(255, 255, 255, 0.62)',
    borderRadius: 999,
    height: 8,
    width: 8,
  },
  activeDot: {
    backgroundColor: '#ffffff',
  },
  overlayActions: {
    flexDirection: 'row',
    gap: 8,
    width: '90%',
  },
  overlayButton: {
    alignItems: 'center',
    backgroundColor: '#E1E9EC',
    borderRadius: 24,
    flex: 1,
    justifyContent: 'center',
    minHeight: 65,
    paddingHorizontal: 16,
  },
  overlayButtonText: {
    color: '#5e686d',
    fontSize: 16,
    fontWeight: '500',
  },
});
