// 일정 생성 화면과 하위 컴포넌트에서 공유하는 스타일입니다.

import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#ffffff',
    flex: 1,
  },
  content: {
    flex: 1,
  },
  stepText: {
    color: '#409CB7',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  heading: {
    color: '#10161F',
    fontWeight: '600',
    lineHeight: 30,
  },
  description: {
    color: '#8A9194',
    fontSize: 12,
    marginTop: 2,
  },
  calendarSection: {
    marginTop: 38,
  },
  calendarHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  monthTitle: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '600',
  },
  monthButtons: {
    flexDirection: 'row',
    gap: 16,
  },
  monthButton: {
    alignItems: 'center',
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  monthButtonText: {
    color: '#10161F',
    fontSize: 38,
    lineHeight: 28,
  },
  disabledMonthButtonText: {
    color: '#DDE3E6',
  },
  weekdayRow: {
    flexDirection: 'row',
    marginTop: 24,
  },
  weekdayText: {
    color: '#10161F',
    flex: 1,
    fontSize: 12,
    textAlign: 'center',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 2,
    minHeight: 264,
  },
  dayCell: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: '14.285714%',
  },
  rangeFill: {
    backgroundColor: '#C9E4EE',
    borderRadius: 999,
    height: 40,
    position: 'absolute',
    width: 40,
  },
  dayText: {
    color: '#8A9194',
    fontSize: 14,
    fontWeight: '400',
    zIndex: 1,
  },
  outsideMonthText: {
    color: '#DCE3E6',
  },
  disabledDayText: {
    color: '#DCE3E6',
  },
  selectedDayText: {
    color: '#10161F',
    fontWeight: '500',
  },
  tripSetupSection: {
    marginTop: 58,
  },
  formLabel: {
    color: '#8A9194',
    fontSize: 12,
    marginBottom: 4,
  },
  inputLine: {
    alignItems: 'center',
    borderBottomColor: '#D6D6D6',
    borderBottomWidth: 1,
    flexDirection: 'row',
    height: 42,
  },
  scheduleInput: {
    color: '#10161F',
    flex: 1,
    fontSize: 24,
    fontWeight: '500',
    height: 42,
    includeFontPadding: false,
    lineHeight: 30,
    padding: 0,
    textAlignVertical: 'center',
  },
  clearButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  clearButtonText: {
    color: '#CECECE',
    fontSize: 32,
    fontWeight: '300',
    lineHeight: 42,
  },
  messageText: {
    color: '#D06958',
    fontSize: 12,
    lineHeight: 17,
    marginBottom: 10,
    textAlign: 'center',
  },
  nextButton: {
    alignItems: 'center',
    backgroundColor: '#6EA4BF',
    borderRadius: 999,
    justifyContent: 'center',
    shadowColor: '#6EA4BF',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.26,
    shadowRadius: 18,
  },
  disabledButton: {
    opacity: 0.65,
  },
  startTripButton: {
    backgroundColor: '#D6EAF5',
    shadowOpacity: 0,
  },
  nextButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '500',
  },
  startTripButtonText: {
    color: '#6EA4BF',
  },
  inviteModalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.24)',
    flex: 1,
    justifyContent: 'flex-end',
    paddingBottom: 63,
    paddingHorizontal: 18,
  },
  invitePanel: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    overflow: 'hidden',
    paddingBottom: 24,
    paddingTop: 28,
    width: '100%',
  },
  invitePanelTitle: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '500',
    paddingHorizontal: 32,
  },
  inviteTopDivider: {
    backgroundColor: '#E8ECEF',
    height: 1,
    marginTop: 22,
  },
  inviteMiddleDivider: {
    backgroundColor: '#E8ECEF',
    height: 1,
  },
  inviteOptionsRow: {
    flexDirection: 'row',
    gap: 8,
    paddingBottom: 14,
    paddingHorizontal: 32,
    paddingTop: 14,
  },
  inviteOption: {
    alignItems: 'center',
    gap: 7,
    width: 66,
  },
  kakaoInviteAvatar: {
    alignItems: 'center',
    backgroundColor: '#FBE339',
    borderRadius: 999,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  kakaoTalkText: {
    color: '#3A2D00',
    fontSize: 9,
    fontWeight: '800',
  },
  inviteContactAvatar: {
    borderRadius: 999,
    height: 56,
    position: 'relative',
    width: 56,
  },
  contactKakaoBadge: {
    alignItems: 'center',
    backgroundColor: '#FBE339',
    borderColor: '#ffffff',
    borderRadius: 999,
    borderWidth: 2,
    bottom: 4,
    height: 23,
    justifyContent: 'center',
    position: 'absolute',
    right: -2,
    width: 23,
  },
  contactKakaoText: {
    color: '#3A2D00',
    fontSize: 5,
    fontWeight: '800',
  },
  inviteOptionText: {
    color: '#54676F',
    fontSize: 12,
    fontWeight: '400',
  },
  copyInviteButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#E9EDF0',
    borderRadius: 16,
    flexDirection: 'row',
    height: 56,
    justifyContent: 'space-between',
    marginTop: 18,
    paddingHorizontal: 34,
    width: '81%',
  },
  copyInviteText: {
    color: '#54676F',
    fontSize: 12,
    fontWeight: '400',
  },
  copyIcon: {
    height: 25,
    position: 'relative',
    width: 25,
  },
  copyIconBack: {
    borderColor: '#54676F',
    borderRadius: 2,
    borderWidth: 2,
    height: 20,
    left: 4,
    position: 'absolute',
    top: 5,
    width: 16,
  },
  copyIconFront: {
    backgroundColor: '#E9EDF0',
    borderColor: '#54676F',
    borderRadius: 2,
    borderWidth: 2,
    height: 20,
    left: 10,
    position: 'absolute',
    top: 0,
    width: 16,
  },
  inviteMessageText: {
    color: '#409CB7',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 10,
    paddingHorizontal: 32,
  },
});
