import { StyleSheet } from 'react-native';

import { MISSION_CARD_HEIGHT, MISSION_CARD_WIDTH } from './mission-capture-data';

// capture 화면의 카메라·미리보기·판정 상태 스타일입니다.
export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#000000',
    flex: 1,
  },
  reviewContainer: {
    backgroundColor: '#F4F7FA',
    flex: 1,
  },
  failureContainer: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    flex: 1,
  },
  failureHeader: {
    alignItems: 'center',
    height: 81,
  },
  failureTitle: {
    color: '#252B30',
    fontSize: 24,
    fontWeight: '600',
    lineHeight: 30,
    textAlign: 'center',
  },
  failureSubtitle: {
    color: '#8A9194',
    fontSize: 12,
    marginTop: 7,
    textAlign: 'center',
  },
  failurePhotoCard: {
    alignSelf: 'center',
    aspectRatio: 3 / 4,
    borderRadius: 20,
    marginTop: 32,
    overflow: 'hidden',
    position: 'relative',
    width: '78%',
  },
  failurePhoto: {
    height: '100%',
    width: '100%',
  },
  failurePhotoOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(10, 18, 24, 0.34)',
  },
  failureMissionCopy: {
    alignItems: 'center',
    left: 24,
    position: 'absolute',
    right: 24,
    top: '41%',
  },
  failureMissionDescription: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 21,
    marginTop: 3,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.45)',
    textShadowOffset: { height: 1, width: 0 },
    textShadowRadius: 4,
  },
  failureRetakeButton: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#BAC0C3',
    borderRadius: 999,
    height: 63,
    justifyContent: 'center',
    marginTop: 'auto',
  },
  failureRetakeButtonText: {
    color: '#5D686C',
    fontSize: 18,
    fontWeight: '500',
  },
  reviewHeader: {
    alignItems: 'center',
    height: 81,
    justifyContent: 'center',
    marginBottom: 32,
    position: 'relative',
  },
  previewTitle: {
    color: '#252B30',
    fontSize: 24,
    fontWeight: '600',
    lineHeight: 30,
    textAlign: 'center',
  },
  previewDescription: {
    color: '#8A9194',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 7,
    textAlign: 'center',
  },
  completeTitle: {
    color: '#2D3C43',
    fontSize: 24,
    fontWeight: '600',
  },
  uploadMessage: {
    color: '#409CB7',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 6,
    textAlign: 'center',
  },
  retakePromptMessage: {
    color: '#2D3C43',
    fontSize: 20,
    fontWeight: '900',
    marginTop: 10,
  },
  judgementLoader: {
    marginTop: 6,
  },
  timeAttackText: {
    color: '#D86C59',
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  timeAttackDanger: {
    color: '#C94435',
  },
  timeAttackBadge: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(18, 24, 32, 0.72)',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  timeAttackBadgeDanger: {
    backgroundColor: 'rgba(201, 68, 53, 0.88)',
  },
  timeAttackBadgeText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
  },
  countdownText: {
    color: '#8A9194',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 5,
    textAlign: 'center',
  },
  previewWrap: {
    alignSelf: 'center',
    aspectRatio: 3 / 4,
    backgroundColor: '#E5EEF3',
    borderRadius: 20,
    overflow: 'hidden',
    position: 'relative',
    width: '78%',
  },
  previewImage: {
    height: '100%',
    width: '100%',
  },
  previewJudgementOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    backgroundColor: 'rgba(13, 23, 29, 0.22)',
    justifyContent: 'center',
  },
  previewJudgementLoader: {
    transform: [{ scale: 1.45 }],
  },
  reviewActions: {
    flexDirection: 'row',
    gap: 18,
    marginTop: 'auto',
  },
  reviewButton: {
    alignItems: 'center',
    borderRadius: 19,
    flex: 1,
    height: 58,
    justifyContent: 'center',
  },
  retakeButton: {
    backgroundColor: '#C9E4EE',
  },
  completeButton: {
    backgroundColor: '#409CB7',
  },
  reviewButtonText: {
    fontSize: 16,
    fontWeight: '500',
  },
  retakeButtonText: {
    color: '#409CB7',
  },
  completeButtonText: {
    color: '#FFFFFF',
  },
  topControls: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 0,
    paddingHorizontal: 22,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 4,
  },
  iconButton: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  closeIcon: {
    height: 17,
    width: 17,
  },
  flashIcon: {
    height: 22,
    width: 22,
  },
  timerControl: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 40,
  },
  timerIcon: {
    height: 23,
    width: 23,
  },
  cameraTimerText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '800',
    position: 'absolute',
    top: 34,
  },
  cameraTimerDanger: {
    color: '#FF7466',
  },
  cameraGuide: {
    bottom: '24%',
    left: 20,
    position: 'absolute',
    right: 20,
    top: '22%',
    zIndex: 1,
  },
  guideCorner: {
    borderColor: '#ffffff',
    height: 90,
    position: 'absolute',
    width: 90,
  },
  guideTopLeft: {
    borderLeftWidth: 4,
    borderTopLeftRadius: 44,
    borderTopWidth: 4,
    left: 0,
    top: 0,
  },
  guideTopRight: {
    borderRightWidth: 4,
    borderTopRightRadius: 44,
    borderTopWidth: 4,
    right: 0,
    top: 0,
  },
  guideBottomLeft: {
    borderBottomLeftRadius: 44,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    bottom: 0,
    left: 0,
  },
  guideBottomRight: {
    borderBottomRightRadius: 44,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    bottom: 0,
    right: 0,
  },
  bottomOverlay: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  backdropOverlay: {
    backgroundColor: '#000000',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 2,
  },
  missionCard: {
    alignSelf: 'center',
    height: MISSION_CARD_HEIGHT,
    position: 'absolute',
    width: MISSION_CARD_WIDTH,
    zIndex: 3,
  },
  captureControls: {
    alignItems: 'center',
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    zIndex: 1,
  },
  shutterOuter: {
    alignItems: 'center',
    backgroundColor: '#E3F0F6',
    borderColor: '#eef3fb',
    borderRadius: 999,
    borderWidth: 5,
    height: 72,
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
    width: 72,
    zIndex: 2,
  },
  shutterInner: {
    backgroundColor: '#ffffff',
    borderRadius: 999,
    height: 62,
    width: 62,
  },
  disabledControl: {
    opacity: 0.62,
  },
  switchButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(227, 240, 246, 0.42)',
    borderRadius: 999,
    height: 50,
    justifyContent: 'center',
    position: 'absolute',
    right: 31,
    width: 50,
  },
  switchIcon: { height: 27, width: 27 },
  stateScreen: {
    alignItems: 'center',
    backgroundColor: '#0c1115',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  permissionCloseButton: {
    alignItems: 'center',
    height: 48,
    justifyContent: 'center',
    left: 22,
    position: 'absolute',
    top: 22,
    width: 48,
  },
  permissionContent: {
    alignItems: 'center',
    width: '100%',
  },
  permissionTitle: {
    color: '#ffffff',
    fontSize: 21,
    fontWeight: '700',
    marginBottom: 10,
  },
  permissionText: {
    color: '#b9c2c9',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 26,
    textAlign: 'center',
  },
  permissionButton: {
    alignItems: 'center',
    backgroundColor: '#c9edf7',
    borderRadius: 999,
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingVertical: 14,
  },
  permissionButtonText: {
    color: '#10161f',
    fontSize: 15,
    fontWeight: '700',
  },
});
