// 프로필 편집 화면에서 사용하는 스타일 모음입니다.
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  keyboardView: {
    backgroundColor: '#ffffff',
    flex: 1,
  },
  container: {
    backgroundColor: '#ffffff',
    flex: 1,
  },
  header: {
    alignItems: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    height: 44,
    justifyContent: 'space-between',
    width: '100%',
  },
  iconButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  headerTitle: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0,
  },
  content: {
    alignSelf: 'center',
    flex: 1,
    width: '100%',
  },
  avatarArea: {
    alignItems: 'center',
    paddingTop: 66,
  },
  avatarButton: {
    height: 110,
    position: 'relative',
    width: 110,
  },
  editBadge: {
    alignItems: 'center',
    backgroundColor: '#CECECE',
    borderRadius: 999,
    bottom: 5,
    height: 30,
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    width: 30,
  },
  formArea: {
    marginTop: 64,
  },
  label: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '500',
    letterSpacing: 0,
  },
  inputRow: {
    alignItems: 'center',
    borderBottomColor: '#E0E0E0',
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 58,
  },
  input: {
    color: '#10161F',
    flex: 1,
    fontSize: 28,
    fontWeight: '700',
    letterSpacing: 0,
    minHeight: 56,
    padding: 0,
  },
  clearButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  messageText: {
    color: '#D35B4F',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 10,
  },
  saveButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#6EA6BF',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 65,
    width: '100%',
  },
  saveButtonDisabled: {
    opacity: 0.55,
  },
  saveButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0,
  },
  modalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000000',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  profileSheet: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 32,
  },
  sheetTitle: {
    color: '#10161F',
    fontSize: 20,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 27,
  },
  sheetPreviewWrap: {
    alignItems: 'center',
    marginTop: 42,
  },
  profileOptionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'center',
    marginTop: 20,
  },
  futureImageOption: {
    alignItems: 'center',
    backgroundColor: '#EFEFEF',
    borderRadius: 999,
    height: 58,
    justifyContent: 'center',
    width: 58,
  },
  profileOptionButton: {
    borderColor: 'transparent',
    borderRadius: 999,
    borderWidth: 3,
    height: 58,
    overflow: 'hidden',
    width: 58,
  },
  profileOptionSelected: {
    borderColor: '#6EA6BF',
  },
  profileOptionImage: {
    height: '100%',
    width: '100%',
  },
  sheetMessageText: {
    color: '#D35B4F',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 12,
    textAlign: 'center',
  },
  sheetActionRow: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 18,
  },
  sheetDeleteButton: {
    alignItems: 'center',
    backgroundColor: '#C9E4EE',
    borderRadius: 18,
    flex: 1,
    height: 58,
    justifyContent: 'center',
  },
  sheetDeleteText: {
    color: '#409CB7',
    fontSize: 16,
    fontWeight: '500',
    letterSpacing: 0,
  },
  sheetSaveButton: {
    alignItems: 'center',
    backgroundColor: '#409CB7',
    borderRadius: 18,
    flex: 1,
    height: 58,
    justifyContent: 'center',
  },
  sheetSaveButtonDisabled: {
    opacity: 0.55,
  },
  sheetSaveText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '500',
    letterSpacing: 0,
  },
});
